"""empty message

Revision ID: dd630414aebb
Revises: 826dc96f706b
Create Date: 2024-12-17 03:02:15.355576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd630414aebb'
down_revision = '826dc96f706b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.create_index('idx_upload_file_account_id', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_index('idx_upload_file_account_id')

    # ### end Alembic commands ###
